on:
  push:
    branches:
      - ja

# kill any builds still running from older commits
concurrency:
  group: deploy-pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
      - name: Fetch Yarn dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: |
          set -euxo pipefail
          yarn run web-js
          yarn run js
          yarn run json
      - name: Package
        run: |
          yarn run prepare
          find docs_out -name .gitignore -delete -print
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs_out
          force_orphan: true
